;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico_w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico_w
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Library dependencies
lib_deps = 
    adafruit/Adafruit MAX31855 library @ ^1.4.1
    br3ttb/PID @ ^1.2.1
    bblanchon/ArduinoJson @ ^6.21.3

; Build options
build_flags = 
    -D ARDUINO_ARCH_RP2040
    -D ARDUINO_RASPBERRY_PI_PICO_W

; Board build options
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
